-- Add profile fields to candidates table
ALTER TABLE candidates 
ADD COLUMN IF NOT EXISTS phone VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS state VARCHAR(255),
ADD COLUMN IF NOT EXISTS "zipCode" VARCHAR(255),
ADD COLUMN IF NOT EXISTS country VARCHAR(255),
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS "hourlyRate" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "experienceYears" INTEGER;
